
# Exploración y Transformación de Datos con Pandas

En este notebook practicarás algunos conceptos fundamentales del análisis de datos:

- Crear nuevas columnas
- Filtrar datos
- Agrupar datos
- Ordenar datos

Pero además trabajarás como lo haría un **analista de datos real**: formulando preguntas y explorando un dataset que te resulte interesante.

---

## Tu misión

1. Escoge un dataset en formato **CSV**.
2. Cárgalo en este notebook.
3. Formula preguntas sobre los datos.
4. Utiliza Pandas para investigarlas.

Ejemplos de datasets que puedes usar:

- ventas de productos
- datos de películas
- estadísticas deportivas
- precios de viviendas
- datos de población

Notebook generado el 2026-03-10

## 1. Importar librerías

In [1]:
import pandas as pd


## 2. Cargar el dataset

Coloca tu archivo CSV en la misma carpeta que este notebook y modifica el nombre del archivo.

In [2]:
file_path = "jobs.csv"

df = pd.read_csv(file_path)

df.head(10)

,title,city,province,price_start,price_end,price_interval,price_currency,description,date,expertise,type,functions,sectors,portal
0,support,Sant Cugat del Vallès,Barcelona,NaN,NaN,NaN,euro,date posted sep 4 2020 location sant cugat ...,2020-10-23,NaN,NaN,NaN,NaN,indeed
1,qa tester,Sant Cugat del Vallès,Barcelona,NaN,NaN,NaN,euro,date posted oct 22 2020 location sant cugat...,2020-10-23,NaN,NaN,NaN,NaN,indeed
2,mathematics consultant,Sant Cugat del Vallès,Barcelona,NaN,NaN,NaN,euro,date posted oct 22 2020 location sant cugat...,2020-10-23,NaN,NaN,NaN,NaN,indeed
3,€1500 mes ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed
4,jovenes €1500 ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed
5,€1500 mes ventas experiencia,Tarragona,Tarragona,NaN,NaN,NaN,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed
6,jovenes €1500 mes trabajando ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos jóvenes trabajar ventas modelo tele t...,2020-10-23,NaN,NaN,NaN,NaN,indeed
7,€1500 mes trabajando ventas internet toda edad,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed
8,atencion jovenes €1500 teletrabajo ventas int...,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas modelo telet...,2020-10-23,NaN,NaN,NaN,NaN,indeed
9,¿quieres teletrabajar casa experiencia formac...,Toledo,Toledo,NaN,NaN,NaN,euro,si emprended r ganas trabajar aprender oport...,2020-10-23,NaN,NaN,NaN,NaN,indeed


## 3. Exploración inicial

Antes de analizar los datos debemos entender el dataset.

Preguntas iniciales:

- ¿Cuántas filas tiene?
- ¿Cuántas columnas?
- ¿Qué tipo de datos hay?

In [11]:
df.shape

(1987, 14)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           1987 non-null   object
 1   city            907 non-null    object
 2   province        1984 non-null   object
 3   price_start     225 non-null    float64
 4   price_end       118 non-null    float64
 5   price_interval  225 non-null    object
 6   price_currency  1987 non-null   object
 7   description     1985 non-null   object
 8   date            1987 non-null   object
 9   expertise       949 non-null    object
 10  type            949 non-null    object
 11  functions       943 non-null    object
 12  sectors         933 non-null    object
 13  portal          1987 non-null   object
dtypes: float64(2), object(12)
memory usage: 217.5+ KB

In [13]:
df.describe()

         price_start      price_end
count     225.000000     118.000000
mean    12710.784444   29177.983051
std     14662.559605   22029.779133
min         8.000000      10.000000
25%       900.000000    3000.000000
50%     12000.000000   30000.000000
75%     20000.000000   50000.000000
max    100000.000000  100000.000000


### Reflexión

Antes de continuar escribe algunas preguntas que te gustaría responder con este dataset.

Por ejemplo:

- ¿Qué categorías tienen valores más altos?
- ¿Hay diferencias entre grupos?
- ¿Qué registros destacan?


# Crear nuevas columnas

En análisis de datos es muy habitual **crear nuevas variables a partir de otras**.

Esto permite:

- generar métricas nuevas
- transformar los datos
- facilitar el análisis


### Ejemplo

```python
df["revenue"] = df["price"] * df["quantity"]
```

In [ ]:
# Ejemplo genérico (puede que no funcione con tu dataset)

df[" "] = df[" "] + df[" "]
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862en,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844en,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602en,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357en,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862en,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0


## Ejercicio 1

Crea una nueva columna en tu dataset.

Ideas:

- combinar columnas
- crear una métrica nueva
- convertir unidades

Motivación:

> ¿Qué nueva variable podría ayudarte a entender mejor los datos?

In [15]:
# Tu solución aquí

# ( 1 )

# df['popularity'] = df['id'].astype(str) + ' ' + df['original_title']

df["salary_avg"] = df[["price_start", "price_end"]].mean(axis=1)

df.head()

,title,city,province,price_start,price_end,price_interval,price_currency,description,date,expertise,type,functions,sectors,portal,salary_avg
0,support,Sant Cugat del Vallès,Barcelona,NaN,NaN,NaN,euro,date posted sep 4 2020 location sant cugat ...,2020-10-23,NaN,NaN,NaN,NaN,indeed,NaN
1,qa tester,Sant Cugat del Vallès,Barcelona,NaN,NaN,NaN,euro,date posted oct 22 2020 location sant cugat...,2020-10-23,NaN,NaN,NaN,NaN,indeed,NaN
2,mathematics consultant,Sant Cugat del Vallès,Barcelona,NaN,NaN,NaN,euro,date posted oct 22 2020 location sant cugat...,2020-10-23,NaN,NaN,NaN,NaN,indeed,NaN
3,€1500 mes ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0
4,jovenes €1500 ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0


# Filtrar datos

Muchas veces queremos analizar **solo una parte del dataset**.

Ejemplo:

```python
df[df["price"] > 100]
```

In [17]:
# Ejemplo genérico
df[df["salary_avg"] > 300]

,title,city,province,price_start,price_end,price_interval,price_currency,description,date,expertise,type,functions,sectors,portal,salary_avg
3,€1500 mes ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0
4,jovenes €1500 ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0
6,jovenes €1500 mes trabajando ventas internet,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos jóvenes trabajar ventas modelo tele t...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0
7,€1500 mes trabajando ventas internet toda edad,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas dedicando 3...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0
8,atencion jovenes €1500 teletrabajo ventas int...,Tarragona,Tarragona,1500.0,NaN,monthly,euro,buscamos personas trabajar ventas modelo telet...,2020-10-23,NaN,NaN,NaN,NaN,indeed,1500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,gestor contratos h m inglés b2,Sant Cugat del Vallès,Barcelona,20000.0,22000.0,yearly,euro,¿en búsqueda nuevo proyecto manpower selecion...,2020-09-23,NaN,NaN,NaN,NaN,indeed,21000.0
993,r expert ivd homebased spain,Madrid,Madrid,50000.0,65000.0,yearly,euro,experience creating developing cancer physiol...,2020-09-23,NaN,NaN,NaN,NaN,indeed,57500.0
998,comercial ventas,Toledo,Toledo,600.0,1500.0,monthly,euro,¿qué buscamos caser seguros personas gusten...,2020-09-23,NaN,NaN,NaN,NaN,indeed,1050.0
1029,consultor financiero,NaN,España,2500.0,5000.0,monthly,euro,busco integrar colaboradores proyecto simples...,2020-09-23,NaN,NaN,NaN,NaN,indeed,3750.0
1033,agente inmobiliario,Palma de Mallorca,Illes Balears,25000.0,40000.0,yearly,euro,keller williams mayor marca inmobiliaria nive...,2020-09-23,NaN,NaN,NaN,NaN,indeed,32500.0


## Ejercicio 2

Filtra el dataset usando una condición.

Motivación:

> ¿Qué subconjunto de los datos sería interesante analizar?

In [18]:
# Tu filtro aquí

df[df["salary_avg"] > 30000]

,title,city,province,price_start,price_end,price_interval,price_currency,description,date,expertise,type,functions,sectors,portal,salary_avg
48,qa automatizado testing sw,Barcelona,Barcelona,33000.0,39000.0,yearly,euro,seleccionamos ingeniero testing qa experienc...,2020-10-23,NaN,NaN,NaN,NaN,indeed,36000.0
74,regional investment representative,Madrid,Madrid,100000.0,NaN,yearly,euro,overview oei sole custodian wealth several sha...,2020-10-22,NaN,NaN,NaN,NaN,indeed,100000.0
84,administrativo a nóminas,l'Hospitalet de Llobregat,Barcelona,35000.0,NaN,yearly,euro,¿te gustaría formar parte empresa lleva 130 añ...,2020-10-22,NaN,NaN,NaN,NaN,indeed,35000.0
152,delivery manager agile scrum,A Coruña provincia,A Coruña,33000.0,52000.0,yearly,euro,actualmente seleccionamos un a delivery manage...,2020-10-21,NaN,NaN,NaN,NaN,indeed,42500.0
195,director franquicia ávila,Ávila,Ávila,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
196,director franquicia baleares,NaN,Illes Balears provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
198,director franquicia rioja,NaN,La Rioja provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
199,director franquicia murcia,Murcia,Murcia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
200,director franquicia bizkaia,NaN,Vizcaya provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
201,director franquicia cantabria,NaN,Cantabria provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
205,director franquicia navarra,NaN,Navarra provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
206,director franquicia toledo,Toledo,Toledo,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
207,director franquicia cuenca,Cuenca,Cuenca,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
208,director franquicia araba,NaN,Álava provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
209,director franquicia asturias,NaN,Asturias provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
210,director franquicia gipuzkoa,NaN,Guipúzcoa provincia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
211,director franquicia guadalajara,Guadalajara,Guadalajara,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
212,director franquicia segovia,Segovia,Segovia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
213,director franquicia palencia,Palencia,Palencia,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
214,director franquicia huesca,Huesca,Huesca,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
215,director franquicia cáceres,Cáceres,Cáceres,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
216,director franquicia jaén,Jaén,Jaén,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
217,director franquicia c tenerife,Tenerife,Santa Cruz de Tenerife,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
218,director franquicia zamora,Zamora,Zamora,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
219,director franquicia girona,Girona,Girona,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
221,director franquicia soria,Soria,Soria,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
223,director franquicia lugo,Lugo,Lugo,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
224,director franquicia cádiz,Cádiz,Cádiz,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
225,director franquicia ourense,Ourense,Ourense,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
228,director franquicia teruel,Teruel,Teruel,12000.0,50000.0,yearly,euro,éxito oposiciones franquicia formación especia...,2020-10-20,NaN,NaN,NaN,NaN,indeed,31000.0
258,consultor integración mulesoft 100 remoto,NaN,En remoto,36000.0,42000.0,yearly,euro,consultor integración mulesoft 100 remoto urg...,2020-10-16,NaN,NaN,NaN,NaN,indeed,39000.0
304,comercial h m,NaN,Catalunya,40000.0,60000.0,yearly,euro,siglo experiencia business consulting combinad...,2020-10-14,NaN,NaN,NaN,NaN,indeed,50000.0
312,service desk process continuous improvement a...,Valencia,Valencia,43000.0,44000.0,yearly,euro,service desk process continuous improvement a...,2020-10-15,NaN,NaN,NaN,NaN,indeed,43500.0
336,director ventas europeo european sales director,Madrid,Madrid,50000.0,100000.0,yearly,euro,entrevistas inglés would like part fast growin...,2020-10-15,NaN,NaN,NaN,NaN,indeed,75000.0
354,inventory manager commercial industrial oper...,Castelló de la Plana,Castellón,32000.0,NaN,yearly,euro,full time role compensation 32k ote € winning...,2020-10-09,NaN,NaN,NaN,NaN,indeed,32000.0
382,technical lead,Barcelona,Barcelona,60000.0,NaN,yearly,euro,looking technical lead join client based spain...,2020-10-16,NaN,NaN,NaN,NaN,indeed,60000.0
440,financial controller,Barcelona,Barcelona,40000.0,60000.0,yearly,euro,company remain confidential interview fast gr...,2020-10-09,NaN,NaN,NaN,NaN,indeed,50000.0
484,implantación dynatrace 100 remoto,NaN,En remoto,42000.0,74000.0,yearly,euro,implantación dynatrace 100 remoto necesitamos...,2020-10-02,NaN,NaN,NaN,NaN,indeed,58000.0
520,administrador tooling ci cd teletrabajo madrid,Madrid,Madrid,42000.0,54000.0,yearly,euro,administrador tooling ci cd teletrabajo madrid...,2020-10-08,NaN,NaN,NaN,NaN,indeed,48000.0
545,devops engineer,Pozuelo de Alarcón,Madrid,52000.0,62000.0,yearly,euro,actualmente seleccionamos devops engineer inco...,2020-10-08,NaN,NaN,NaN,NaN,indeed,57000.0
637,director a comercial exportación división educ...,Valladolid,Valladolid,40000.0,60000.0,yearly,euro,importante empresa comercio internacional prec...,2020-10-01,NaN,NaN,NaN,NaN,indeed,50000.0
701,field service engineer medical diagonostic eq...,NaN,En remoto,40000.0,60000.0,yearly,euro,field service engineer medical diagnostic equ...,2020-09-23,NaN,NaN,NaN,NaN,indeed,50000.0
759,responsable desarrollo negocio,Madrid,Madrid,35000.0,NaN,yearly,euro,¿quién cliente compañía experta identificar g...,2020-09-23,NaN,NaN,NaN,NaN,indeed,35000.0
765,salesforce consultant multinacional cliente f...,Madrid,Madrid,45000.0,NaN,yearly,euro,oportunidad profesional salesforce consultant ...,2020-09-23,NaN,NaN,NaN,NaN,indeed,45000.0
795,responsable web madrid,Madrid,Madrid,39000.0,45000.0,yearly,euro,responsable web madrid ¿quieres desarrollar ca...,2020-09-23,NaN,NaN,NaN,NaN,indeed,42000.0
896,director comercial exportación maquinaria enva...,Valladolid,Valladolid,40000.0,50000.0,yearly,euro,importante empresa comercio internacional prec...,2020-09-23,NaN,NaN,NaN,NaN,indeed,45000.0
909,product owner project manager 100 remoto,NaN,En remoto,24000.0,42000.0,yearly,euro,product owner project manager 100 remoto apr...,2020-09-23,NaN,NaN,NaN,NaN,indeed,33000.0
922,data support seguridad arquitectura,A Coruña provincia,A Coruña,30000.0,48000.0,yearly,euro,requisitos mínimos requiere habilidades mínim...,2020-09-23,NaN,NaN,NaN,NaN,indeed,39000.0
923,technical product owner apis,A Coruña provincia,A Coruña,36000.0,44000.0,yearly,euro,actualmente seleccionamos un a product owner i...,2020-09-23,NaN,NaN,NaN,NaN,indeed,40000.0
924,auditor a sw arquitectura qa,A Coruña provincia,A Coruña,27000.0,39000.0,yearly,euro,ampliando equipo technology desarrollar proyec...,2020-09-23,NaN,NaN,NaN,NaN,indeed,33000.0
925,data support,A Coruña provincia,A Coruña,30000.0,48000.0,yearly,euro,requisitos mínimos requiere data support habi...,2020-09-23,NaN,NaN,NaN,NaN,indeed,39000.0
962,key account manager,Madrid,Madrid,33000.0,NaN,yearly,euro,key account manager control€xpert gmbh spain ...,2020-09-23,NaN,NaN,NaN,NaN,indeed,33000.0
974,gerente investigación españa,Barcelona,Barcelona,50000.0,NaN,yearly,euro,equipo dedicado españa caza próximo gerente in...,2020-09-23,NaN,NaN,NaN,NaN,indeed,50000.0
977,supplier quality technician,Igualada,Barcelona,33000.0,42000.0,yearly,euro,proach selecciona supplier quality technician ...,2020-09-23,NaN,NaN,NaN,NaN,indeed,37500.0
993,r expert ivd homebased spain,Madrid,Madrid,50000.0,65000.0,yearly,euro,experience creating developing cancer physiol...,2020-09-23,NaN,NaN,NaN,NaN,indeed,57500.0
1033,agente inmobiliario,Palma de Mallorca,Illes Balears,25000.0,40000.0,yearly,euro,keller williams mayor marca inmobiliaria nive...,2020-09-23,NaN,NaN,NaN,NaN,indeed,32500.0


## Ejercicio 3 — Múltiples condiciones

Podemos combinar condiciones usando:

- `&` (AND)
- `|` (OR)

In [ ]:
# Ejemplo
# df[(df["col1"] > 10) & (df["col2"] < 50)]

In [ ]:
# Tu solución aquí
df[(df["city"].str.lower() == "madrid") & (df["salary_avg"] > 30000)]

,title,city,province,price_start,price_end,price_interval,price_currency,description,date,expertise,type,functions,sectors,portal,salary_avg
74,regional investment representative,Madrid,Madrid,100000.0,NaN,yearly,euro,overview oei sole custodian wealth several sha...,2020-10-22,NaN,NaN,NaN,NaN,indeed,100000.0
336,director ventas europeo european sales director,Madrid,Madrid,50000.0,100000.0,yearly,euro,entrevistas inglés would like part fast growin...,2020-10-15,NaN,NaN,NaN,NaN,indeed,75000.0
520,administrador tooling ci cd teletrabajo madrid,Madrid,Madrid,42000.0,54000.0,yearly,euro,administrador tooling ci cd teletrabajo madrid...,2020-10-08,NaN,NaN,NaN,NaN,indeed,48000.0
759,responsable desarrollo negocio,Madrid,Madrid,35000.0,NaN,yearly,euro,¿quién cliente compañía experta identificar g...,2020-09-23,NaN,NaN,NaN,NaN,indeed,35000.0
765,salesforce consultant multinacional cliente f...,Madrid,Madrid,45000.0,NaN,yearly,euro,oportunidad profesional salesforce consultant ...,2020-09-23,NaN,NaN,NaN,NaN,indeed,45000.0
795,responsable web madrid,Madrid,Madrid,39000.0,45000.0,yearly,euro,responsable web madrid ¿quieres desarrollar ca...,2020-09-23,NaN,NaN,NaN,NaN,indeed,42000.0
962,key account manager,Madrid,Madrid,33000.0,NaN,yearly,euro,key account manager control€xpert gmbh spain ...,2020-09-23,NaN,NaN,NaN,NaN,indeed,33000.0
993,r expert ivd homebased spain,Madrid,Madrid,50000.0,65000.0,yearly,euro,experience creating developing cancer physiol...,2020-09-23,NaN,NaN,NaN,NaN,indeed,57500.0


# Agrupar datos

La función **groupby()** permite resumir información por categorías.

Ejemplo:

```python
df.groupby("category")["price"].mean()
```

In [ ]:
# Ejemplo genérico
# df.groupby("columna_categoria").mean()


## Ejercicio 4

Agrupa el dataset por una columna categórica y calcula una estadística.

Motivación:

> ¿Cómo cambian los valores dependiendo de la categoría?

In [28]:
# Tu agrupación aquí
df.groupby("province")["salary_avg"].mean().sort_values(ascending=False)

province
Catalunya                  50000.000000
Valladolid                 39333.333333
Illes Balears              32500.000000
A Coruña                   32408.333333
Castellón                  32000.000000
                               ...
Uña                                 NaN
Valencia y alrededores              NaN
Valencia/València                   NaN
Vigo                                NaN
Villanueva de la Cañada             NaN
Name: salary_avg, Length: 95, dtype: float64


## Ejercicio 5 — Agrupación por varias columnas

In [27]:
# Tu solución aquí
df.groupby(["province", "type"])["salary_avg"].mean().reset_index().sort_values(by="salary_avg", ascending=False)

                   province               type  salary_avg
0                Alcobendas   Jornada completa         NaN
1                  Alicante   Jornada completa         NaN
2          Alicante/Alacant   Jornada completa         NaN
3                   Almería   Jornada completa         NaN
4                  Asturias   Jornada completa         NaN
..                      ...                ...         ...
86               Valladolid   Jornada completa         NaN
87                     Vigo      Media jornada         NaN
88  Villanueva de la Cañada   Jornada completa         NaN
89                 Zaragoza  Contrato por obra         NaN
90                 Zaragoza   Jornada completa         NaN

[91 rows x 3 columns]


# Ordenar datos

Ordenar permite identificar rápidamente:

- valores máximos
- valores mínimos
- registros destacados

In [ ]:
# Ejemplo
#bdf.sort_values("columna")


## Ejercicio 6

Ordena tu dataset por una columna.

Prueba:

- orden ascendente
- orden descendente

In [26]:
# Tu ordenación aquí
df.sort_values("salary_avg", ascending=False).head(10)

,title,city,province,price_start,price_end,price_interval,price_currency,description,date,expertise,type,functions,sectors,portal,salary_avg
74,regional investment representative,Madrid,Madrid,100000.0,NaN,yearly,euro,overview oei sole custodian wealth several sha...,2020-10-22,NaN,NaN,NaN,NaN,indeed,100000.0
336,director ventas europeo european sales director,Madrid,Madrid,50000.0,100000.0,yearly,euro,entrevistas inglés would like part fast growin...,2020-10-15,NaN,NaN,NaN,NaN,indeed,75000.0
382,technical lead,Barcelona,Barcelona,60000.0,NaN,yearly,euro,looking technical lead join client based spain...,2020-10-16,NaN,NaN,NaN,NaN,indeed,60000.0
484,implantación dynatrace 100 remoto,NaN,En remoto,42000.0,74000.0,yearly,euro,implantación dynatrace 100 remoto necesitamos...,2020-10-02,NaN,NaN,NaN,NaN,indeed,58000.0
993,r expert ivd homebased spain,Madrid,Madrid,50000.0,65000.0,yearly,euro,experience creating developing cancer physiol...,2020-09-23,NaN,NaN,NaN,NaN,indeed,57500.0
545,devops engineer,Pozuelo de Alarcón,Madrid,52000.0,62000.0,yearly,euro,actualmente seleccionamos devops engineer inco...,2020-10-08,NaN,NaN,NaN,NaN,indeed,57000.0
304,comercial h m,NaN,Catalunya,40000.0,60000.0,yearly,euro,siglo experiencia business consulting combinad...,2020-10-14,NaN,NaN,NaN,NaN,indeed,50000.0
440,financial controller,Barcelona,Barcelona,40000.0,60000.0,yearly,euro,company remain confidential interview fast gr...,2020-10-09,NaN,NaN,NaN,NaN,indeed,50000.0
637,director a comercial exportación división educ...,Valladolid,Valladolid,40000.0,60000.0,yearly,euro,importante empresa comercio internacional prec...,2020-10-01,NaN,NaN,NaN,NaN,indeed,50000.0
974,gerente investigación españa,Barcelona,Barcelona,50000.0,NaN,yearly,euro,equipo dedicado españa caza próximo gerente in...,2020-09-23,NaN,NaN,NaN,NaN,indeed,50000.0


# Desafío final

Combina varias operaciones:

1. Filtra datos
2. Agrupa
3. Ordena el resultado

In [ ]:
# Tu análisis final aquí

df_filtered = df[(df["salary_avg"].notna()) & (df["type"] == "Full-time")]

resultado_final = df_filtered.groupby("province")["salary_avg"].mean().reset_index()

resultado_final.sort_values(by="salary_avg", ascending=False)

Empty DataFrame
Columns: [province, salary_avg]
Index: []


# Reflexión final

Responde:

1. ¿ Qué dataset utilizaste ?

# He utilizado un dataset de ofertas de trabajo llamado jobs.csv.

2. ¿ Qué preguntas querías responder ?

# Quería ver en qué ciudades y provincias hay mejores sueldos y
# Tipos de empleo.


3. ¿ Qué descubriste ?

# Descubrí que muchas ofertas no tienen salario informado,
# pero entre las que sí lo tienen se pueden comparar en que provincias y trabajos.

4. ¿ Qué operación de Pandas fue más útil ?

# La que más me ayudó fue groupby(), porque permite resumir datos mas fácil.